### ISSUE TITLE
Switch to Jest

### ISSUE THREAD

**Issue by thibaudcolas** [springload/frontend-starter-kit#18]
I'd like to change our testing tools from Mocha + Chai to Jest. 
- [x] Migrate the starter kit tests (in a PR so we can see what the differences are)
- [x] Would snapshot testing of React components be useful for us? (https://facebook.github.io/jest/blog/2016/07/27/jest-14.html)
- [ ] What are the bare minimum tests for a React component that would be helpful and very easy to set up? https://gist.github.com/thevangelist/e2002bc6b9834def92d46e4d92f15874

**Comment by thibaudcolas** [comment]
Ping @vincentaudebert re snapshot testing & "bare minimum tests"

**Comment by vincentaudebert** [comment]
Regarding bare minimum tests, using snapshots it would consist into filling just the required properties for each components.
cf: https://github.com/springload/frontend-starter-kit/commit/77106e425dcf2a512916634beda8c0a1bae7246f#diff-364e82eee4a6d78ac7b972628ec06b4fR6

**Comment by thibaudcolas** [comment]
Merged!
