### ISSUE TITLE
Sass errors are hard to read

### ISSUE THREAD

**Issue by laurarbunea** [springload/frontend-starter-kit#67]
Can the sass errors show after all of the styleguide components are getting read... as the errors are easily missed

**Comment by thibaudcolas** [comment]
@laurarbunea what do you mean exactly? In what command? (screenshot welcome)

**Comment by laurarbunea** [comment]
![screen shot 2017-05-29 at 2 30 39 pm](https://cloud.githubusercontent.com/assets/20081576/26534747/7298d8fa-447b-11e7-85fc-7eb3e332220a.png)
see how the components get listed at the bottom and the sass errors above it is there anychance to swap them ? i can never see if i have any errorrs without scrolling up

**Comment by thibaudcolas** [comment]
👍  @laurarbunea the stylesheets have to be compiled before the pattern library generation, but I'll see if we can change this tool so it's not as verbose.

See https://github.com/emiloberg/markdown-styleguide-generator/issues/13.

**Comment by holloway** [comment]
Not sure if this is needed any more. Reopen if it's an issue.
