### ISSUE TITLE
Create gulpfile.js folder

### ISSUE THREAD

**Issue by mr-winter** [springload/frontend-starter-kit#7]
What do you guys think of moving the gulpfile and the tasks into a `gulpfile.js` folder? I've seen this approach on Wagtail and it would help to bundle up things a bit more.

**Comment by ThibWeb** [comment]
Hmmm do you have an example of that? I thought the `gulpfile.js` needed to be at the project's root, in this case is it relying on the fact that Node will load an `index.js` inside that folder?

**Comment by mr-winter** [comment]
Yup. https://github.com/torchbox/wagtail/tree/master/gulpfile.js <https://github.com/torchbox/wagtail/tree/master/gulpfile.js>

**Comment by ThibWeb** [comment]
Sorry Thomas I changed my comment a lot after looking for the example myself hehe

**Comment by mr-winter** [comment]
Let's do it then. Perhaps a job for @vincentaudebert when he's light again. Please remember to also update the `springtail-cookiecutter`.

**Comment by vincentaudebert** [comment]
Yeah I'm kinda looking into frontend-starter-kit now. I'll check this one.

**Comment by ThibWeb** [comment]
Done in this repo and I finished the job in https://github.com/springload/springtail-cookiecutter/blob/master/hooks/post_gen_project.sh.
