### ISSUE TITLE
Switch to webpack 2

### ISSUE THREAD

**Issue by JoshBarr** [springload/frontend-starter-kit#8]
Browserify is slow and makes large bundles. We should move to Webpack :+1:

**Comment by ThibWeb** [comment]
One more reason to make the move https://github.com/reactjs/react-router/pull/3503. I would already be on it if the webpack configuration wasn't so horrible and we could have feature parity with our current tools... and webpack 2 wasn't on the way.

**Comment by ThibWeb** [comment]
More links worth checking out

https://github.com/petehunt/webpack-howto
https://github.com/js-dxtools/webpack-validator
https://github.com/Browsersync/recipes/tree/master/recipes/webpack.babel

**Comment by thibaudcolas** [comment]
Let's copy how https://github.com/facebookincubator/create-react-app is configured when we get to this.

**Comment by thibaudcolas** [comment]
Assigned to @vincentaudebert, to be worked on when webpack 2 is marked `@latest` on npm (see https://www.npmjs.com/package/webpack), inspired by the configurations from https://github.com/facebookincubator/create-react-app/pull/1291.

For now please keep it to the JS build, with 1 entry point and 1 "common chunks" for vendor dependencies, and integration with `browser-sync`.
