### ISSUE TITLE
Should we add a CHANGELOG to this project?

### ISSUE THREAD

**Issue by thibaudcolas** [springload/frontend-starter-kit#85]
Over time there are quite many things happening in here, components or tools being added or removed, new documentation. 

Would people find it interesting to have a file listing all of the changes? It's a bit of effort to maintain a changelog over time, but if there is enough interest that's totally worth it.

Here is an example of a project that has a detailed changelog, we would use a similar format here: https://github.com/springload/draftjs_exporter/blob/master/CHANGELOG.md

Edit: and potentially version it as well? It sounds a bit superfluous but it may be interesting to have some indication of how likely changes are to be breaking.

**Comment by holloway** [comment]
Yes, yes we should :smile: 

https://github.com/springload/frontend-starter-kit/blob/master/CHANGELOG.md
