### ISSUE TITLE
Create Accessibility one pager

### ISSUE THREAD

**Issue by samanthaksanders** [springload/frontend-starter-kit#89]
There is a brief thing here linking to a blog post but we could probably expand on this
https://github.com/springload/frontend-starter-kit/tree/master/docs

A lot like the css one, basic must do's to check off? This sorta lives here. But this page is very hidden
https://github.com/springload/frontend-starter-kit/blob/master/docs/frontend-launch-checklist.md#accessibility

**Comment by katie-day** [comment]
Here are some good resources for accessibility here: https://frontendmasters.com/books/front-end-handbook/2018/tools/accessibility.html - could be helpful in creating our one pager

**Comment by katie-day** [comment]
In progress here: https://github.com/springload/frontend-starter-kit/blob/master/docs/html.md

**Comment by holloway** [comment]
Done
